namespace LogGenerator
{
    using Serilog;
    using System.Threading.Tasks;

    class Program
    {
        static async Task Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .Enrich.WithProperty("App", "FakeService")
                .WriteTo.Console()
                .CreateLogger();

            var credsUrl = "https://iincident-sentinel.s3.us-east-1.amazonaws.com/credentials.json";
            var logger = new CloudWatchLogger("PaymentApiLogs", "autogenerated", credsUrl);

            var runner = new SimulationRunner(logger);
            await runner.RunSimulationAsync();
        }
    }


}
